Implemented stub background source

diff --git a/functions/fuzzy-match b/functions/fuzzy-match
--- a/functions/fuzzy-match
+++ b/functions/fuzzy-match
@@ -1,4 +1,3 @@
-# some snippets/ideas were taken from github/zsh-users/zaw
 fuzzy-match() {
 	emulate -L zsh
 	setopt local_options extended_glob
@@ -21,8 +20,12 @@ fuzzy-match() {
 	# widget-specific state, global for easy sharing across functions.
 	state=(
 		nl '[[:IFS:]]'
-		selected_line 1
+		selected_line 0
 		last_selected_line 0
+		max_lines $(($LINES - 2)) # 1 line for the prompt, another for status
+		max_columns $COLUMNS
+		lines 0
+		incomplete_line ''
 	)
 
 	# initialize configuration
@@ -33,7 +36,38 @@ fuzzy-match() {
 	zstyle -s ':fuzzy-match:highlight' title "state[hi_title]" ||\
 	 	state[hi_title]='bold'
 
-	POSTDISPLAY=$'\nTesting\nline\nnavigation\n'
+	# initialize source program
+	#
+	# it can be any program that will listen on standard input for search
+	# patterns, and send back results to standard output.
+	#
+	# there's no input protocol, each input line represents a search pattern. if
+	# the source is still searching for
+	#
+	# the output protocol only two possible types of message:
+	# CLEAR: clear the results
+	# APPEND-RESULT: append a single matched result
+	#
+	local source_prog=$1
+	if [[ -z $source_prog ]]; then
+		source_prog="_fuzzy-match-file-glob"
+	fi
+
+	# create ipc named fifo
+	local ipc_pipe=$(mktemp -u --suffix=-fuzzy-match)
+	while ! mkfifo -m 600 $ipc_pipe; do
+		ipc_pipe=$(mktemp -u --suffix=-fuzzy-match)
+	done
+
+	# open the pipe for reading/writing
+	exec 3<> $ipc_pipe
+
+	# make zle listen on the pipe
+	zle -F 3 _fuzzy-match-update-results
+
+	# start the source prog with input/output redirected to the ipc_pipe
+	$source_prog $state[max_lines] > $ipc_pipe < $ipc_pipe &!
+	local source_pid=$!
 
 	# Intercept self-insert, {up,down}-line-or-history
 	zle -N self-insert _fuzzy-match-self-insert
@@ -58,13 +92,50 @@ fuzzy-match() {
 	if [[ -n $old_state[region_highlight] ]]; then
 		region_highlight=("$old_state[region_highlight][@]")
 	fi
+
+	# refresh
 	zle -Rc
+
+	# delete globals set
 	unset old_state state IFS
+
+	# cleanup source process
+	kill $source_pid &> /dev/null
+	exec 3>&-
+	rm -f $ipc_pipe
 
 	# if interrupted, just exit and don't do anything else
 	(( edit_status )) && zle send-break
 
 	printf "done"
+}
+
+_fuzzy-match-update-results() {
+	local cmd item
+	if read -u 3 cmd; then
+		case $cmd in
+			CLEAR*)
+				POSTDISPLAY=''
+				state[lines]=0
+				state[selected_line]=0
+				state[last_selected_line]=0
+				;;
+			APPEND-RESULT:*)
+				item=${cmd#APPEND\-RESULT\:}
+				POSTDISPLAY+=$'\n'
+				POSTDISPLAY+="$item"
+				(( state[lines]++ ))
+				if (( state[selected_line] == 0 )); then
+					# automatically select the first line
+					local hi_selected=$state[hi_selected]
+					state[selected_line]=1
+					region_highlight[1]="1 $(( $#item + 1)) $hi_selected"
+				fi
+				state[incomplete_line]=''
+				;;
+		esac
+		zle -Rc
+	fi
 }
 
 zle -N fuzzy-match
